name: Build and Test for Dev and Feature Branches

# Trigger workflow on push to 'dev' branch or 'feature/*' branches
on:
  push:
    branches:
      - dev
      - features/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/mywebsite:dev-latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/mywebsite:dev-latest
